//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1Demo2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class Kullanici : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Mesaj[] GonderenKullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResimYoluField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Rol RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.UserFriend[] UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.DegerlendirmeDurumu[] UserAppointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.UserFriend[] UserJobFriendField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Mesaj[] GonderenKullanici {
            get {
                return this.GonderenKullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.GonderenKullaniciField, value) != true)) {
                    this.GonderenKullaniciField = value;
                    this.RaisePropertyChanged("GonderenKullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResimYolu {
            get {
                return this.ResimYoluField;
            }
            set {
                if ((object.ReferenceEquals(this.ResimYoluField, value) != true)) {
                    this.ResimYoluField = value;
                    this.RaisePropertyChanged("ResimYolu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Rol Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.UserFriend[] User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.DegerlendirmeDurumu[] UserAppoint {
            get {
                return this.UserAppointField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAppointField, value) != true)) {
                    this.UserAppointField = value;
                    this.RaisePropertyChanged("UserAppoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.UserFriend[] UserJobFriend {
            get {
                return this.UserJobFriendField;
            }
            set {
                if ((object.ReferenceEquals(this.UserJobFriendField, value) != true)) {
                    this.UserJobFriendField = value;
                    this.RaisePropertyChanged("UserJobFriend");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.Mesaj))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.Proje))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.DegerlendirmeDurumu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.Gorev))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.ProjectMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.Rol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.UserFriend))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfServiceLibrary1Demo2.ServiceReference1.Kullanici))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesaj", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class Mesaj : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GelisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GonderenGelisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici GonderenKullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GonderenKullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici KullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Proje ProjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.ProjectMessage ProjectMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectMessageIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GelisTarihi {
            get {
                return this.GelisTarihiField;
            }
            set {
                if ((this.GelisTarihiField.Equals(value) != true)) {
                    this.GelisTarihiField = value;
                    this.RaisePropertyChanged("GelisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> GonderenGelisTarihi {
            get {
                return this.GonderenGelisTarihiField;
            }
            set {
                if ((this.GonderenGelisTarihiField.Equals(value) != true)) {
                    this.GonderenGelisTarihiField = value;
                    this.RaisePropertyChanged("GonderenGelisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici GonderenKullanici {
            get {
                return this.GonderenKullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.GonderenKullaniciField, value) != true)) {
                    this.GonderenKullaniciField = value;
                    this.RaisePropertyChanged("GonderenKullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GonderenKullaniciId {
            get {
                return this.GonderenKullaniciIdField;
            }
            set {
                if ((this.GonderenKullaniciIdField.Equals(value) != true)) {
                    this.GonderenKullaniciIdField = value;
                    this.RaisePropertyChanged("GonderenKullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici {
            get {
                return this.KullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciField, value) != true)) {
                    this.KullaniciField = value;
                    this.RaisePropertyChanged("Kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MesajAdi {
            get {
                return this.MesajAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajAdiField, value) != true)) {
                    this.MesajAdiField = value;
                    this.RaisePropertyChanged("MesajAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Proje Proje {
            get {
                return this.ProjeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeField, value) != true)) {
                    this.ProjeField = value;
                    this.RaisePropertyChanged("Proje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjeId {
            get {
                return this.ProjeIdField;
            }
            set {
                if ((this.ProjeIdField.Equals(value) != true)) {
                    this.ProjeIdField = value;
                    this.RaisePropertyChanged("ProjeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.ProjectMessage ProjectMessage {
            get {
                return this.ProjectMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectMessageField, value) != true)) {
                    this.ProjectMessageField = value;
                    this.RaisePropertyChanged("ProjectMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectMessageId {
            get {
                return this.ProjectMessageIdField;
            }
            set {
                if ((this.ProjectMessageIdField.Equals(value) != true)) {
                    this.ProjectMessageIdField = value;
                    this.RaisePropertyChanged("ProjectMessageId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proje", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class Proje : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifBitmediField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BaslangicTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BitisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.DegerlendirmeDurumu[] DegerlendirmeDurumusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GizlilikAktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Gorev[] GorevsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici KullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjeAciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjeAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SistemBaslamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YoneticiKullaniciIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AktifBitmedi {
            get {
                return this.AktifBitmediField;
            }
            set {
                if ((this.AktifBitmediField.Equals(value) != true)) {
                    this.AktifBitmediField = value;
                    this.RaisePropertyChanged("AktifBitmedi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaslangicTarihi {
            get {
                return this.BaslangicTarihiField;
            }
            set {
                if ((this.BaslangicTarihiField.Equals(value) != true)) {
                    this.BaslangicTarihiField = value;
                    this.RaisePropertyChanged("BaslangicTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BitisTarihi {
            get {
                return this.BitisTarihiField;
            }
            set {
                if ((this.BitisTarihiField.Equals(value) != true)) {
                    this.BitisTarihiField = value;
                    this.RaisePropertyChanged("BitisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.DegerlendirmeDurumu[] DegerlendirmeDurumus {
            get {
                return this.DegerlendirmeDurumusField;
            }
            set {
                if ((object.ReferenceEquals(this.DegerlendirmeDurumusField, value) != true)) {
                    this.DegerlendirmeDurumusField = value;
                    this.RaisePropertyChanged("DegerlendirmeDurumus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GizlilikAktif {
            get {
                return this.GizlilikAktifField;
            }
            set {
                if ((this.GizlilikAktifField.Equals(value) != true)) {
                    this.GizlilikAktifField = value;
                    this.RaisePropertyChanged("GizlilikAktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Gorev[] Gorevs {
            get {
                return this.GorevsField;
            }
            set {
                if ((object.ReferenceEquals(this.GorevsField, value) != true)) {
                    this.GorevsField = value;
                    this.RaisePropertyChanged("Gorevs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici {
            get {
                return this.KullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciField, value) != true)) {
                    this.KullaniciField = value;
                    this.RaisePropertyChanged("Kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjeAciklama {
            get {
                return this.ProjeAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeAciklamaField, value) != true)) {
                    this.ProjeAciklamaField = value;
                    this.RaisePropertyChanged("ProjeAciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjeAdi {
            get {
                return this.ProjeAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeAdiField, value) != true)) {
                    this.ProjeAdiField = value;
                    this.RaisePropertyChanged("ProjeAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjeId {
            get {
                return this.ProjeIdField;
            }
            set {
                if ((this.ProjeIdField.Equals(value) != true)) {
                    this.ProjeIdField = value;
                    this.RaisePropertyChanged("ProjeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sira {
            get {
                return this.SiraField;
            }
            set {
                if ((this.SiraField.Equals(value) != true)) {
                    this.SiraField = value;
                    this.RaisePropertyChanged("Sira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SistemBaslamaTarihi {
            get {
                return this.SistemBaslamaTarihiField;
            }
            set {
                if ((this.SistemBaslamaTarihiField.Equals(value) != true)) {
                    this.SistemBaslamaTarihiField = value;
                    this.RaisePropertyChanged("SistemBaslamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YoneticiKullaniciId {
            get {
                return this.YoneticiKullaniciIdField;
            }
            set {
                if ((this.YoneticiKullaniciIdField.Equals(value) != true)) {
                    this.YoneticiKullaniciIdField = value;
                    this.RaisePropertyChanged("YoneticiKullaniciId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DegerlendirmeDurumu", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class DegerlendirmeDurumu : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici AtayanKullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AtayanKullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Gorev GorevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GorevIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlerlemeDurumAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici KullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Proje ProjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PuanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici AtayanKullanici {
            get {
                return this.AtayanKullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.AtayanKullaniciField, value) != true)) {
                    this.AtayanKullaniciField = value;
                    this.RaisePropertyChanged("AtayanKullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AtayanKullaniciId {
            get {
                return this.AtayanKullaniciIdField;
            }
            set {
                if ((this.AtayanKullaniciIdField.Equals(value) != true)) {
                    this.AtayanKullaniciIdField = value;
                    this.RaisePropertyChanged("AtayanKullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Gorev Gorev {
            get {
                return this.GorevField;
            }
            set {
                if ((object.ReferenceEquals(this.GorevField, value) != true)) {
                    this.GorevField = value;
                    this.RaisePropertyChanged("Gorev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GorevId {
            get {
                return this.GorevIdField;
            }
            set {
                if ((this.GorevIdField.Equals(value) != true)) {
                    this.GorevIdField = value;
                    this.RaisePropertyChanged("GorevId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlerlemeDurumAdi {
            get {
                return this.IlerlemeDurumAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IlerlemeDurumAdiField, value) != true)) {
                    this.IlerlemeDurumAdiField = value;
                    this.RaisePropertyChanged("IlerlemeDurumAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici {
            get {
                return this.KullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciField, value) != true)) {
                    this.KullaniciField = value;
                    this.RaisePropertyChanged("Kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Proje Proje {
            get {
                return this.ProjeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeField, value) != true)) {
                    this.ProjeField = value;
                    this.RaisePropertyChanged("Proje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjeId {
            get {
                return this.ProjeIdField;
            }
            set {
                if ((this.ProjeIdField.Equals(value) != true)) {
                    this.ProjeIdField = value;
                    this.RaisePropertyChanged("ProjeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Puan {
            get {
                return this.PuanField;
            }
            set {
                if ((this.PuanField.Equals(value) != true)) {
                    this.PuanField = value;
                    this.RaisePropertyChanged("Puan");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gorev", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class Gorev : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifBitmediField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GizlilikAktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GorevAciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GorevAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GorevBaslangicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GorevBitisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GorevIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GorevOncelikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici KullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Proje ProjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SistemBaslamaTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AktifBitmedi {
            get {
                return this.AktifBitmediField;
            }
            set {
                if ((this.AktifBitmediField.Equals(value) != true)) {
                    this.AktifBitmediField = value;
                    this.RaisePropertyChanged("AktifBitmedi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GizlilikAktif {
            get {
                return this.GizlilikAktifField;
            }
            set {
                if ((this.GizlilikAktifField.Equals(value) != true)) {
                    this.GizlilikAktifField = value;
                    this.RaisePropertyChanged("GizlilikAktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GorevAciklama {
            get {
                return this.GorevAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.GorevAciklamaField, value) != true)) {
                    this.GorevAciklamaField = value;
                    this.RaisePropertyChanged("GorevAciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GorevAdi {
            get {
                return this.GorevAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.GorevAdiField, value) != true)) {
                    this.GorevAdiField = value;
                    this.RaisePropertyChanged("GorevAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GorevBaslangic {
            get {
                return this.GorevBaslangicField;
            }
            set {
                if ((this.GorevBaslangicField.Equals(value) != true)) {
                    this.GorevBaslangicField = value;
                    this.RaisePropertyChanged("GorevBaslangic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GorevBitis {
            get {
                return this.GorevBitisField;
            }
            set {
                if ((this.GorevBitisField.Equals(value) != true)) {
                    this.GorevBitisField = value;
                    this.RaisePropertyChanged("GorevBitis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GorevId {
            get {
                return this.GorevIdField;
            }
            set {
                if ((this.GorevIdField.Equals(value) != true)) {
                    this.GorevIdField = value;
                    this.RaisePropertyChanged("GorevId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GorevOncelik {
            get {
                return this.GorevOncelikField;
            }
            set {
                if ((object.ReferenceEquals(this.GorevOncelikField, value) != true)) {
                    this.GorevOncelikField = value;
                    this.RaisePropertyChanged("GorevOncelik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici {
            get {
                return this.KullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciField, value) != true)) {
                    this.KullaniciField = value;
                    this.RaisePropertyChanged("Kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Proje Proje {
            get {
                return this.ProjeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeField, value) != true)) {
                    this.ProjeField = value;
                    this.RaisePropertyChanged("Proje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjeId {
            get {
                return this.ProjeIdField;
            }
            set {
                if ((this.ProjeIdField.Equals(value) != true)) {
                    this.ProjeIdField = value;
                    this.RaisePropertyChanged("ProjeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sira {
            get {
                return this.SiraField;
            }
            set {
                if ((this.SiraField.Equals(value) != true)) {
                    this.SiraField = value;
                    this.RaisePropertyChanged("Sira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SistemBaslamaTarihi {
            get {
                return this.SistemBaslamaTarihiField;
            }
            set {
                if ((this.SistemBaslamaTarihiField.Equals(value) != true)) {
                    this.SistemBaslamaTarihiField = value;
                    this.RaisePropertyChanged("SistemBaslamaTarihi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectMessage", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class ProjectMessage : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Proje ProjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectConversationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Proje Proje {
            get {
                return this.ProjeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeField, value) != true)) {
                    this.ProjeField = value;
                    this.RaisePropertyChanged("Proje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectConversation {
            get {
                return this.ProjectConversationField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectConversationField, value) != true)) {
                    this.ProjectConversationField = value;
                    this.RaisePropertyChanged("ProjectConversation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class Rol : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> TipiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Tipi {
            get {
                return this.TipiField;
            }
            set {
                if ((this.TipiField.Equals(value) != true)) {
                    this.TipiField = value;
                    this.RaisePropertyChanged("Tipi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFriend", Namespace="http://schemas.datacontract.org/2004/07/DYS.Common.VO")]
    [System.SerializableAttribute()]
    public partial class UserFriend : WcfServiceLibrary1Demo2.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserJobFriendIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktive {
            get {
                return this.AktiveField;
            }
            set {
                if ((this.AktiveField.Equals(value) != true)) {
                    this.AktiveField = value;
                    this.RaisePropertyChanged("Aktive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici1 {
            get {
                return this.Kullanici1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Kullanici1Field, value) != true)) {
                    this.Kullanici1Field = value;
                    this.RaisePropertyChanged("Kullanici1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici Kullanici2 {
            get {
                return this.Kullanici2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Kullanici2Field, value) != true)) {
                    this.Kullanici2Field = value;
                    this.RaisePropertyChanged("Kullanici2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserJobFriendId {
            get {
                return this.UserJobFriendIdField;
            }
            set {
                if ((this.UserJobFriendIdField.Equals(value) != true)) {
                    this.UserJobFriendIdField = value;
                    this.RaisePropertyChanged("UserJobFriendId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.ProjectModel")]
    [System.SerializableAttribute()]
    public partial class ProjectModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel.TaskModel[] TaskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectEndDate {
            get {
                return this.ProjectEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectEndDateField, value) != true)) {
                    this.ProjectEndDateField = value;
                    this.RaisePropertyChanged("ProjectEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectStartDate {
            get {
                return this.ProjectStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectStartDateField, value) != true)) {
                    this.ProjectStartDateField = value;
                    this.RaisePropertyChanged("ProjectStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectTitle {
            get {
                return this.ProjectTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectTitleField, value) != true)) {
                    this.ProjectTitleField = value;
                    this.RaisePropertyChanged("ProjectTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel.TaskModel[] Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ProjectModel.TaskModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.ProjectModel")]
        [System.SerializableAttribute()]
        public partial class TaskModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int TaskIdField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TaskTitleField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int TaskId {
                get {
                    return this.TaskIdField;
                }
                set {
                    if ((this.TaskIdField.Equals(value) != true)) {
                        this.TaskIdField = value;
                        this.RaisePropertyChanged("TaskId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string TaskTitle {
                get {
                    return this.TaskTitleField;
                }
                set {
                    if ((object.ReferenceEquals(this.TaskTitleField, value) != true)) {
                        this.TaskTitleField = value;
                        this.RaisePropertyChanged("TaskTitle");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.UserModel")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProjectModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.UserModel")]
    [System.SerializableAttribute()]
    public partial class UserProjectModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyTaskModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.UserModel")]
    [System.SerializableAttribute()]
    public partial class MyTaskModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsNowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailModel MyTaskDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDateStr {
            get {
                return this.EndDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateStrField, value) != true)) {
                    this.EndDateStrField = value;
                    this.RaisePropertyChanged("EndDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsNow {
            get {
                return this.IsNowField;
            }
            set {
                if ((this.IsNowField.Equals(value) != true)) {
                    this.IsNowField = value;
                    this.RaisePropertyChanged("IsNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailModel MyTaskDetail {
            get {
                return this.MyTaskDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.MyTaskDetailField, value) != true)) {
                    this.MyTaskDetailField = value;
                    this.RaisePropertyChanged("MyTaskDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDateStr {
            get {
                return this.StartDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateStrField, value) != true)) {
                    this.StartDateStrField = value;
                    this.RaisePropertyChanged("StartDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="MyTaskModel.MyTaskDetailModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.UserModel")]
        [System.SerializableAttribute()]
        public partial class MyTaskDetailModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ByUserNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string SystemStartDateField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TaskDetailField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ByUserName {
                get {
                    return this.ByUserNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.ByUserNameField, value) != true)) {
                        this.ByUserNameField = value;
                        this.RaisePropertyChanged("ByUserName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SystemStartDate {
                get {
                    return this.SystemStartDateField;
                }
                set {
                    if ((object.ReferenceEquals(this.SystemStartDateField, value) != true)) {
                        this.SystemStartDateField = value;
                        this.RaisePropertyChanged("SystemStartDate");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string TaskDetail {
                get {
                    return this.TaskDetailField;
                }
                set {
                    if ((object.ReferenceEquals(this.TaskDetailField, value) != true)) {
                        this.TaskDetailField = value;
                        this.RaisePropertyChanged("TaskDetail");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="MyTaskModel.MyTaskDetailStatusModel", Namespace="http://schemas.datacontract.org/2004/07/servisdemo13.BASE.UserModel")]
        [System.SerializableAttribute()]
        public partial class MyTaskDetailStatusModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool IsTaskStatuField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsTaskStatu {
                get {
                    return this.IsTaskStatuField;
                }
                set {
                    if ((this.IsTaskStatuField.Equals(value) != true)) {
                        this.IsTaskStatuField = value;
                        this.RaisePropertyChanged("IsTaskStatu");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetUser", ReplyAction="urn:IService1/GetUserResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.Kullanici[] GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetTask", ReplyAction="urn:IService1/GetTaskResponse")]
        string GetTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetGorevOne", ReplyAction="urn:IService1/GetGorevOneResponse")]
        string GetGorevOne(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetProTask", ReplyAction="urn:IService1/GetProTaskResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel[] GetProTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetTaskList", ReplyAction="urn:IService1/GetTaskListResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel.TaskModel[] GetTaskList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/DeleteTask", ReplyAction="urn:IService1/DeleteTaskResponse")]
        string DeleteTask(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/Login", ReplyAction="urn:IService1/LoginResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.UserModel Login(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetProject", ReplyAction="urn:IService1/GetProjectResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.UserProjectModel[] GetProject(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetUserTask", ReplyAction="urn:IService1/GetUserTaskResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel[] GetUserTask(string userId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetMyTask", ReplyAction="urn:IService1/GetMyTaskResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel[] GetMyTask(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/GetTaskDetail", ReplyAction="urn:IService1/GetTaskDetailResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailModel GetTaskDetail(string userId, string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IService1/SetTaskStatus", ReplyAction="urn:IService1/SetTaskStatusResponse")]
        WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailStatusModel SetTaskStatus(string taskId, string isTaskStatu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceLibrary1Demo2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceLibrary1Demo2.ServiceReference1.IService1>, WcfServiceLibrary1Demo2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.Kullanici[] GetUser() {
            return base.Channel.GetUser();
        }
        
        public string GetTask() {
            return base.Channel.GetTask();
        }
        
        public string GetGorevOne(string id) {
            return base.Channel.GetGorevOne(id);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel[] GetProTask() {
            return base.Channel.GetProTask();
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.ProjectModel.TaskModel[] GetTaskList() {
            return base.Channel.GetTaskList();
        }
        
        public string DeleteTask(string id) {
            return base.Channel.DeleteTask(id);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.UserModel Login(string userEmail, string userPassword) {
            return base.Channel.Login(userEmail, userPassword);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.UserProjectModel[] GetProject(string userId) {
            return base.Channel.GetProject(userId);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel[] GetUserTask(string userId, string projectId) {
            return base.Channel.GetUserTask(userId, projectId);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel[] GetMyTask(string userId) {
            return base.Channel.GetMyTask(userId);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailModel GetTaskDetail(string userId, string taskId) {
            return base.Channel.GetTaskDetail(userId, taskId);
        }
        
        public WcfServiceLibrary1Demo2.ServiceReference1.MyTaskModel.MyTaskDetailStatusModel SetTaskStatus(string taskId, string isTaskStatu) {
            return base.Channel.SetTaskStatus(taskId, isTaskStatu);
        }
    }
}
